
// All symbols generated by tokenizer for parser //////////////////////////////////////////////////
enum Symbols {
    Array,
    Begin,
    By,
    Case,
    Const,
    Continue,
    Definition,
    Div,
    Do,
    Else,
    Elsif,
    End,
    Exit,
    False,
    For,
    If,
    Import,
    In,
    Is,
    Loop,
    Mod,
    Module,
    Nil,
    Of,
    Or,
    Pointer,
    Proc,
    Procedure,
    Record,
    Repeat,
    Return,
    Then,
    To,
    True,
    Type,
    Until,
    Var,
    While,
    With,

    Minus,
    Comma,
    Semicolon,
    Colon,
    ColonAssign,
    Upto, // ..
    LeftParen,
    RightParen,
    LeftBracket,
    RightBracket,
    LeftCurly,
    RightCurly,
    Multiply,
    Slash,
    NotEqual,
    Arrow,
    Plus,
    Less,
    LessEqual,
    Equal,
    Greater,
    GreaterEqual,
    Bar,
    Tilde,
    Ambersand, // &

    Ident,
    Number,
    String,
    HexString,
    HexChar,


    Unknown
}

// Abstract Syntax tree nodes generated by parser /////////////////////////////////////////////////
enum AST {
    Relation_Equal(Box<AST>, Box<AST>),
    Relation_NotEqual(Box<AST>, Box<AST>),
    Relation_Less(Box<AST>, Box<AST>),
    Relation_LessEqual(Box<AST>, Box<AST>),
    Relation_Greater(Box<AST>, Box<AST>),
    Relation_GreaterEqual(Box<AST>, Box<AST>),
    Relation_In(Box<AST>, Box<AST>),
    Relation_Is(Box<AST>, Box<AST>),
    AddOperator_Plus(Box<AST>, Box<AST>),
    AddOperator_Minus(Box<AST>, Box<AST>),
    AddOperator_Or(Box<AST>, Box<AST>),
    Unary_Plus(Box<AST>),
    Unary_Minus(Box<AST>),
    MulOperator_Multiply(Box<AST>, Box<AST>),
    MulOperator_Slash(Box<AST>, Box<AST>),
    MulOperator_Div(Box<AST>, Box<AST>),
    MulOperator_Mod(Box<AST>, Box<AST>),
    MulOperator_AmbersAnd(Box<AST>, Box<AST>),
    Factor_Tilde(Box<AST>),
    Literal_True(u32, u32),
    Literal_False(u32, u32),
    Literal_Nil(u32, u32),
    Literal_Number(u32, u32, String),
    Literal_String(u32, u32, String),
    Literal_HexString(u32, u32, String),
    Literal_HexChar(u32, u32, String),
    Set(Vec<Box<AST>>),
    Element(Box<AST>, Box<AST>)
}


// Trait for Parser and Lexical analyzer methods //////////////////////////////////////////////////
pub trait parser_rules {
    fn new(source: String) -> Parser;
    fn advance(&mut self) -> ();

    /* Expression parse rules */
    fn expression(&mut self) -> Result<Box<AST>, String>;
    fn simple_expression(&mut self) -> Result<Box<AST>, String>;
    fn term(&mut self) -> Result<Box<AST>, String>;
    fn factor(&mut self) -> Result<Box<AST>, String>;
    fn literal(&mut self) -> Result<Box<AST>, String>;
    fn set(&mut self) -> Result<Box<AST>, String>;
    fn element(&mut self) -> Result<Box<AST>, String>;
}


// Parser for oberon //////////////////////////////////////////////////////////////////////////////
pub struct Parser {
    symbol: Symbols,
    line: u32,
    column: u32,
    buffer: String,
    source: String
}


// Oberon language parser and tokenizer methods ///////////////////////////////////////////////////
impl parser_rules for Parser {
    fn new(source: String) -> Self {
        Parser {
            symbol: Symbols::Unknown,
            line: 1,
            column: 1,
            buffer: "".to_string(),
            source: source
        }
    }

    fn advance(&mut self) -> () {

    }

    /* Expression rules */

    fn expression(&mut self) -> Result<Box<AST>, String> {
        let left = self.simple_expression()?; 
        match self.symbol {
            Symbols::Equal => {
                self.advance();
                Ok(Box::new(AST::Relation_Equal(left, self.simple_expression()?)))
            },
            Symbols::NotEqual => {
                self.advance();
                Ok(Box::new(AST::Relation_NotEqual(left, self.simple_expression()?)))
            },
            Symbols::Less => {
                self.advance();
                Ok(Box::new(AST::Relation_Less(left, self.simple_expression()?)))
            },
            Symbols::LessEqual => {
                self.advance();
                Ok(Box::new(AST::Relation_LessEqual(left, self.simple_expression()?)))
            },
            Symbols::Greater => {
                self.advance();
                Ok(Box::new(AST::Relation_Greater(left, self.simple_expression()?)))
            },
            Symbols::GreaterEqual => {
                self.advance();
                Ok(Box::new(AST::Relation_GreaterEqual(left, self.simple_expression()?)))
            },
            Symbols::In => {
                self.advance();
                Ok(Box::new(AST::Relation_In(left, self.simple_expression()?)))
            },
            Symbols::Is => {
                self.advance();
                Ok(Box::new(AST::Relation_Is(left, self.simple_expression()?)))
            },
            _ =>
                Ok(left)
        }
    }

    fn simple_expression(&mut self) -> Result<Box<AST>, String> {
        let left = match self.symbol {
            Symbols::Plus => {
                self.advance();
                Box::new(AST::Unary_Plus(self.term()?))
            },
            Symbols::Minus => {
                self.advance();
                Box::new(AST::Unary_Minus(self.term()?))
            },
            _ => self.term()?
        };
        match self.symbol {
            Symbols::Plus => {
                self.advance();
                Ok(Box::new(AST::AddOperator_Plus(left, self.term()?)))
            },
            Symbols::Minus => {
                self.advance();
                Ok(Box::new(AST::AddOperator_Minus(left, self.term()?)))
            },
            Symbols::Or => {
                self.advance();
                Ok(Box::new(AST::AddOperator_Or(left, self.term()?)))
            },
            _ => Ok(left)
        }
    }

    fn term(&mut self) -> Result<Box<AST>, String> {
        let left = self.factor()?;
        match self.symbol {
            Symbols::Multiply => {
                self.advance();
                Ok(Box::new(AST::MulOperator_Multiply(left, self.factor()?)))
            },
            Symbols::Slash => {
                self.advance();
                Ok(Box::new(AST::MulOperator_Slash(left, self.factor()?)))
            },
            Symbols::Div => {
                self.advance();
                Ok(Box::new(AST::MulOperator_Div(left, self.factor()?)))
            },
            Symbols::Mod => {
                self.advance();
                Ok(Box::new(AST::MulOperator_Mod(left, self.factor()?)))
            },
            Symbols::Ambersand => {
                self.advance();
                Ok(Box::new(AST::MulOperator_AmbersAnd(left, self.factor()?)))
            },
            _ => Ok(left)
        }
    }

    fn factor(&mut self) -> Result<Box<AST>, String> {
        match self.symbol {
            Symbols::Tilde => {
                self.advance();
                Ok(Box::new(AST::Factor_Tilde(self.factor()?)))
            },
            Symbols::LeftParen => {
                self.advance();
                let left = self.expression()?;
                match self.symbol {
                    Symbols::RightParen => {
                        self.advance();
                        Ok(left)
                    },
                    _ => Err(format!("Syntax Error! At line: {}, column: {} in file: {} - Missing closing `)` in expression.", self.line, self.column, self.source))
                }
            },
            Symbols::Ident => {
                todo!()
            }
            _ => self.literal()
        }
    }

    fn literal(&mut self) -> Result<Box<AST>, String> {
        let line = self.line; let col = self.column;
        match self.symbol {
            Symbols::Number => {
                let buffer = self.buffer.clone();
                self.advance();
                Ok(Box::new(AST::Literal_Number(line, col, buffer)))
            },
            Symbols::String => {
                let buffer = self.buffer.clone();
                self.advance();
                Ok(Box::new(AST::Literal_String(line, col, buffer)))
            },
            Symbols::HexString => {
                let buffer = self.buffer.clone();
                self.advance();
                Ok(Box::new(AST::Literal_HexString(line, col, buffer)))
            },
            Symbols::HexChar => {
                let buffer = self.buffer.clone();
                self.advance();
                Ok(Box::new(AST::Literal_HexChar(line, col, buffer)))
            },
            Symbols::Nil => {
                self.advance();
                Ok(Box::new(AST::Literal_Nil(line, col)))
            },
            Symbols::True => {
                self.advance();
                Ok(Box::new(AST::Literal_True(line, col)))
            },
            Symbols::False => {
                self.advance();
                Ok(Box::new(AST::Literal_False(line, col)))
            },
            Symbols::LeftCurly => {
                self.set()
            },
            _ => Err(format!("Syntax Error! At line: {}, column: {} in file: {} - Missing literal.", self.line, self.column, self.source))
        }
    }

    fn set(&mut self) -> Result<Box<AST>, String> {
        let mut elements = Vec::<Box<AST>>::new();
        self.advance();
        match self.symbol {
            Symbols::RightCurly => {
                self.advance();
                Ok(Box::new(AST::Set(elements)))
            },
            _ => {
                elements.push(self.element()?);
                loop {
                    match self.symbol {
                        Symbols::Comma => {
                            self.advance();
                            elements.push(self.element()?);
                        },
                        _ => break
                    }
                }
                match self.symbol {
                    Symbols::RightCurly => {
                        self.advance();
                        Ok(Box::new(AST::Set(elements)))
                    },
                    _ => Err(format!("Syntax Error! At line: {}, column: {} in file: {} - Missing closing parenthesis in set.", self.line, self.column, self.source))
                }
            }
        }
    }

    fn element(&mut self) -> Result<Box<AST>, String> {
        let left = self.expression()?;
        match self.symbol {
            Symbols::Upto => {
                self.advance();
                Ok(Box::new(AST::Element(left, self.expression()?)))
            },
            _ => Ok(left)
        }
    }

    
}