
// All symbols generated by tokenizer for parser //////////////////////////////////////////////////
enum Symbols {
    Array,
    Begin,
    By,
    Case,
    Const,
    Continue,
    Definition,
    Div,
    Do,
    Else,
    Elsif,
    End,
    Exit,
    False,
    For,
    If,
    Import,
    In,
    Is,
    Loop,
    Mod,
    Module,
    Nil,
    Of,
    Or,
    Pointer,
    Proc,
    Procedure,
    Record,
    Repeat,
    Return,
    Then,
    To,
    True,
    Type,
    Until,
    Var,
    While,
    With,

    Minus,
    Comma,
    Semicolon,
    Colon,
    ColonAssign,
    Upto, // ..
    LeftParen,
    RightParen,
    LeftBracket,
    RightBracket,
    LeftCurly,
    RightCurly,
    Multiply,
    Slash,
    NotEqual,
    Arrow,
    Plus,
    Less,
    LessEqual,
    Equal,
    Greater,
    GreaterEqual,
    Bar,
    Tilde,
    Ambersand, // &


    Unknown
}

// Abstract Syntax tree nodes generated by parser /////////////////////////////////////////////////
enum AST {
    Relation_Equal(Box<AST>, Box<AST>),
    Relation_NotEqual(Box<AST>, Box<AST>),
    Relation_Less(Box<AST>, Box<AST>),
    Relation_LessEqual(Box<AST>, Box<AST>),
    Relation_Greater(Box<AST>, Box<AST>),
    Relation_GreaterEqual(Box<AST>, Box<AST>),
    Relation_In(Box<AST>, Box<AST>),
    Relation_Is(Box<AST>, Box<AST>),
}


// Trait for Parser and Lexical analyzer methods //////////////////////////////////////////////////
pub trait parser_rules {
    fn new() -> Parser;
    fn advance(&mut self) -> ();

    /* Expression parse rules */
    fn expression(&mut self) -> Result<Box<AST>, String>;
    fn simple_expression(&mut self) -> Result<Box<AST>, String>;   
}


// Parser for oberon //////////////////////////////////////////////////////////////////////////////
pub struct Parser {
    symbol: Symbols
}


// Oberon language parser and tokenizer methods ///////////////////////////////////////////////////
impl parser_rules for Parser {
    fn new() -> Self {
        Parser {
            symbol: Symbols::Unknown
        }
    }

    fn advance(&mut self) -> () {

    }

    /* Expression rules */
    
    fn expression(&mut self) -> Result<Box<AST>, String> {
        let mut left = self.simple_expression()?; 
        match self.symbol {
            Symbols::Equal => {
                self.advance();
                Ok(Box::new(AST::Relation_Equal(left, self.simple_expression()?)))
            },
            Symbols::NotEqual => {
                self.advance();
                Ok(Box::new(AST::Relation_NotEqual(left, self.simple_expression()?)))
            },
            Symbols::Less => {
                self.advance();
                Ok(Box::new(AST::Relation_Less(left, self.simple_expression()?)))
            },
            Symbols::LessEqual => {
                self.advance();
                Ok(Box::new(AST::Relation_LessEqual(left, self.simple_expression()?)))
            },
            Symbols::Greater => {
                self.advance();
                Ok(Box::new(AST::Relation_Greater(left, self.simple_expression()?)))
            },
            Symbols::GreaterEqual => {
                self.advance();
                Ok(Box::new(AST::Relation_GreaterEqual(left, self.simple_expression()?)))
            },
            Symbols::In => {
                self.advance();
                Ok(Box::new(AST::Relation_In(left, self.simple_expression()?)))
            },
            Symbols::Is => {
                self.advance();
                Ok(Box::new(AST::Relation_Is(left, self.simple_expression()?)))
            },
            _ =>
                Ok(left)
        }
    }

    fn simple_expression(&mut self) -> Result<Box<AST>, String> {
        Err("".to_string())
    }
}