
// All symbols generated by tokenizer for parser //////////////////////////////////////////////////
enum Symbols {
    Array,
    Begin,
    By,
    Case,
    Const,
    Continue,
    Definition,
    Div,
    Do,
    Else,
    Elsif,
    End,
    Exit,
    False,
    For,
    If,
    Import,
    In,
    Is,
    Loop,
    Mod,
    Module,
    Nil,
    Of,
    Or,
    Pointer,
    Proc,
    Procedure,
    Record,
    Repeat,
    Return,
    Then,
    To,
    True,
    Type,
    Until,
    Var,
    While,
    With,

    Minus,
    Comma,
    Semicolon,
    Colon,
    ColonAssign,
    Upto, // ..
    LeftParen,
    RightParen,
    LeftBracket,
    RightBracket,
    LeftCurly,
    RightCurly,
    Multiply,
    Slash,
    NotEqual,
    Arrow,
    Plus,
    Less,
    LessEqual,
    Equal,
    Greater,
    GreaterEqual,
    Bar,
    Tilde,
    Ambersand, // &
    Period,

    Ident,
    Number,
    String,
    HexString,
    HexChar,


    Unknown
}

// Abstract Syntax tree nodes generated by parser /////////////////////////////////////////////////
enum AST {
    Relation_Equal(Box<AST>, Box<AST>),
    Relation_NotEqual(Box<AST>, Box<AST>),
    Relation_Less(Box<AST>, Box<AST>),
    Relation_LessEqual(Box<AST>, Box<AST>),
    Relation_Greater(Box<AST>, Box<AST>),
    Relation_GreaterEqual(Box<AST>, Box<AST>),
    Relation_In(Box<AST>, Box<AST>),
    Relation_Is(Box<AST>, Box<AST>),
    AddOperator_Plus(Box<AST>, Box<AST>),
    AddOperator_Minus(Box<AST>, Box<AST>),
    AddOperator_Or(Box<AST>, Box<AST>),
    Unary_Plus(Box<AST>),
    Unary_Minus(Box<AST>),
    MulOperator_Multiply(Box<AST>, Box<AST>),
    MulOperator_Slash(Box<AST>, Box<AST>),
    MulOperator_Div(Box<AST>, Box<AST>),
    MulOperator_Mod(Box<AST>, Box<AST>),
    MulOperator_AmbersAnd(Box<AST>, Box<AST>),
    Factor_Tilde(Box<AST>),
    Literal_True(u32, u32),
    Literal_False(u32, u32),
    Literal_Nil(u32, u32),
    Literal_Number(u32, u32, String),
    Literal_String(u32, u32, String),
    Literal_HexString(u32, u32, String),
    Literal_HexChar(u32, u32, String),
    Set(Vec<Box<AST>>),
    Element(Box<AST>, Box<AST>),
    DesignatorWithActualParameters(Box<AST>, Box<AST>),
    ExprList(Vec<Box<AST>>),
    ActualParameters(Option<Box<AST>>),
    Qualident(u32, u32, String, u32, u32, String),
    Name(u32, u32, String),
    Designator(Box<AST>, Box<AST>),
    Arrow,
    Index(Option<Box<AST>>),
    Call(Option<Box<AST>>)
}


// Trait for Parser and Lexical analyzer methods //////////////////////////////////////////////////
pub trait ParseRules {
    fn new(source: String) -> Parser;
    fn advance(&mut self) -> ();

    /* Expression parse rules */
    fn expression(&mut self) -> Result<Box<AST>, String>;
    fn simple_expression(&mut self) -> Result<Box<AST>, String>;
    fn term(&mut self) -> Result<Box<AST>, String>;
    fn factor(&mut self) -> Result<Box<AST>, String>;
    fn literal(&mut self) -> Result<Box<AST>, String>;
    fn set(&mut self) -> Result<Box<AST>, String>;
    fn element(&mut self) -> Result<Box<AST>, String>;
    fn designator(&mut self) -> Result<Box<AST>, String>;
    fn selector(&mut self) -> Result<Box<AST>, String>;
    fn expr_list(&mut self) -> Result<Box<AST>, String>;
    fn actual_parameters(&mut self) -> Result<Box<AST>, String>;
    fn qualident(&mut self) -> Result<Box<AST>, String>;

    /* Statement parse rules */
    fn statement(&mut self) -> Result<Box<AST>, String>;
    fn if_statement(&mut self) -> Result<Box<AST>, String>;
    fn case_tatement(&mut self) -> Result<Box<AST>, String>;
    fn with_statement(&mut self) -> Result<Box<AST>, String>;
    fn loop_statement(&mut self) -> Result<Box<AST>, String>;
    fn exit_statement(&mut self) -> Result<Box<AST>, String>;
    fn return_statement(&mut self) -> Result<Box<AST>, String>;
    fn while_statement(&mut self) -> Result<Box<AST>, String>;
    fn repeat_statement(&mut self) -> Result<Box<AST>, String>;
    fn for_statement(&mut self) -> Result<Box<AST>, String>;
    fn procedure_call(&mut self) -> Result<Box<AST>, String>;
    fn assignment(&mut self) -> Result<Box<AST>, String>;
}


// Parser for oberon //////////////////////////////////////////////////////////////////////////////
pub struct Parser {
    symbol: Symbols,
    line: u32,
    column: u32,
    buffer: String,
    source: String
}


// Oberon language parser and tokenizer methods ///////////////////////////////////////////////////
impl ParseRules for Parser {
    fn new(source: String) -> Self {
        Parser {
            symbol: Symbols::Unknown,
            line: 1,
            column: 1,
            buffer: "".to_string(),
            source: source
        }
    }

    fn advance(&mut self) -> () {

    }

    /* Expression rules */

    fn expression(&mut self) -> Result<Box<AST>, String> {
        let left = self.simple_expression()?; 
        match self.symbol {
            Symbols::Equal => {
                self.advance();
                Ok(Box::new(AST::Relation_Equal(left, self.simple_expression()?)))
            },
            Symbols::NotEqual => {
                self.advance();
                Ok(Box::new(AST::Relation_NotEqual(left, self.simple_expression()?)))
            },
            Symbols::Less => {
                self.advance();
                Ok(Box::new(AST::Relation_Less(left, self.simple_expression()?)))
            },
            Symbols::LessEqual => {
                self.advance();
                Ok(Box::new(AST::Relation_LessEqual(left, self.simple_expression()?)))
            },
            Symbols::Greater => {
                self.advance();
                Ok(Box::new(AST::Relation_Greater(left, self.simple_expression()?)))
            },
            Symbols::GreaterEqual => {
                self.advance();
                Ok(Box::new(AST::Relation_GreaterEqual(left, self.simple_expression()?)))
            },
            Symbols::In => {
                self.advance();
                Ok(Box::new(AST::Relation_In(left, self.simple_expression()?)))
            },
            Symbols::Is => {
                self.advance();
                Ok(Box::new(AST::Relation_Is(left, self.simple_expression()?)))
            },
            _ =>
                Ok(left)
        }
    }

    fn simple_expression(&mut self) -> Result<Box<AST>, String> {
        let left = match self.symbol {
            Symbols::Plus => {
                self.advance();
                Box::new(AST::Unary_Plus(self.term()?))
            },
            Symbols::Minus => {
                self.advance();
                Box::new(AST::Unary_Minus(self.term()?))
            },
            _ => self.term()?
        };
        match self.symbol {
            Symbols::Plus => {
                self.advance();
                Ok(Box::new(AST::AddOperator_Plus(left, self.term()?)))
            },
            Symbols::Minus => {
                self.advance();
                Ok(Box::new(AST::AddOperator_Minus(left, self.term()?)))
            },
            Symbols::Or => {
                self.advance();
                Ok(Box::new(AST::AddOperator_Or(left, self.term()?)))
            },
            _ => Ok(left)
        }
    }

    fn term(&mut self) -> Result<Box<AST>, String> {
        let left = self.factor()?;
        match self.symbol {
            Symbols::Multiply => {
                self.advance();
                Ok(Box::new(AST::MulOperator_Multiply(left, self.factor()?)))
            },
            Symbols::Slash => {
                self.advance();
                Ok(Box::new(AST::MulOperator_Slash(left, self.factor()?)))
            },
            Symbols::Div => {
                self.advance();
                Ok(Box::new(AST::MulOperator_Div(left, self.factor()?)))
            },
            Symbols::Mod => {
                self.advance();
                Ok(Box::new(AST::MulOperator_Mod(left, self.factor()?)))
            },
            Symbols::Ambersand => {
                self.advance();
                Ok(Box::new(AST::MulOperator_AmbersAnd(left, self.factor()?)))
            },
            _ => Ok(left)
        }
    }

    fn factor(&mut self) -> Result<Box<AST>, String> {
        match self.symbol {
            Symbols::Tilde => {
                self.advance();
                Ok(Box::new(AST::Factor_Tilde(self.factor()?)))
            },
            Symbols::LeftParen => {
                self.advance();
                let left = self.expression()?;
                match self.symbol {
                    Symbols::RightParen => {
                        self.advance();
                        Ok(left)
                    },
                    _ => Err(format!("Syntax Error! At line: {}, column: {} in file: {} - Missing closing `)` in expression.", self.line, self.column, self.source))
                }
            },
            Symbols::Ident => {
                let left = self.designator()?;
                match self.symbol {
                    Symbols::LeftParen => {
                        let right = self.actual_parameters()?;
                        Ok(Box::new(AST::DesignatorWithActualParameters(left, right)))
                    },
                    _ => Ok(left)
                }
            }
            _ => self.literal()
        }
    }

    fn literal(&mut self) -> Result<Box<AST>, String> {
        let line = self.line; let col = self.column;
        match self.symbol {
            Symbols::Number => {
                let buffer = self.buffer.clone();
                self.advance();
                Ok(Box::new(AST::Literal_Number(line, col, buffer)))
            },
            Symbols::String => {
                let buffer = self.buffer.clone();
                self.advance();
                Ok(Box::new(AST::Literal_String(line, col, buffer)))
            },
            Symbols::HexString => {
                let buffer = self.buffer.clone();
                self.advance();
                Ok(Box::new(AST::Literal_HexString(line, col, buffer)))
            },
            Symbols::HexChar => {
                let buffer = self.buffer.clone();
                self.advance();
                Ok(Box::new(AST::Literal_HexChar(line, col, buffer)))
            },
            Symbols::Nil => {
                self.advance();
                Ok(Box::new(AST::Literal_Nil(line, col)))
            },
            Symbols::True => {
                self.advance();
                Ok(Box::new(AST::Literal_True(line, col)))
            },
            Symbols::False => {
                self.advance();
                Ok(Box::new(AST::Literal_False(line, col)))
            },
            Symbols::LeftCurly => {
                self.set()
            },
            _ => Err(format!("Syntax Error! At line: {}, column: {} in file: {} - Missing literal.", self.line, self.column, self.source))
        }
    }

    fn set(&mut self) -> Result<Box<AST>, String> {
        let mut elements = Vec::<Box<AST>>::new();
        self.advance();
        match self.symbol {
            Symbols::RightCurly => {
                self.advance();
                Ok(Box::new(AST::Set(elements)))
            },
            _ => {
                elements.push(self.element()?);
                loop {
                    match self.symbol {
                        Symbols::Comma => {
                            self.advance();
                            elements.push(self.element()?);
                        },
                        _ => break
                    }
                }
                match self.symbol {
                    Symbols::RightCurly => {
                        self.advance();
                        Ok(Box::new(AST::Set(elements)))
                    },
                    _ => Err(format!("Syntax Error! At line: {}, column: {} in file: {} - Missing closing parenthesis in set.", self.line, self.column, self.source))
                }
            }
        }
    }

    fn element(&mut self) -> Result<Box<AST>, String> {
        let left = self.expression()?;
        match self.symbol {
            Symbols::Upto => {
                self.advance();
                Ok(Box::new(AST::Element(left, self.expression()?)))
            },
            _ => Ok(left)
        }
    }

    fn designator(&mut self) -> Result<Box<AST>, String> {
        let left = self.qualident()?;
        match self.symbol {
            Symbols::Period |
            Symbols::Arrow |
            Symbols::LeftBracket |
            Symbols::LeftParen => {
                let right = self.selector()?;
                Ok(Box::new(AST::Designator(left, right)))
            },
            _ => Ok(left)
        }
    }

    fn selector(&mut self) -> Result<Box<AST>, String> {
        match self.symbol {
            Symbols::Arrow => {
                self.advance();
                Ok(Box::new(AST::Arrow))
            },
            Symbols::Period => {
                self.advance();
                match self.symbol {
                    Symbols::Ident => {
                        let line = self.line; let col = self.column; let buffer = self.buffer.clone();
                        self.advance();
                        Ok(Box::new(AST::Name(line, col, buffer)))
                    },
                    _ => Err(format!("Syntax Error! At line: {}, column: {} in file: {} - Missing Name after `.` in selector.", self.line, self.column, self.source))
                }
            },
            Symbols::LeftBracket => {
                self.advance();
                match self.symbol {
                    Symbols::RightBracket => {
                        self.advance();
                        Ok(Box::new(AST::Index(None)))
                    },
                    _ => {
                        let node = self.expr_list()?;
                        match self.symbol {
                            Symbols::RightBracket => {
                                self.advance();
                                Ok(Box::new(AST::Index(Some(node))))
                            },
                            _ => Err(format!("Syntax Error! At line: {}, column: {} in file: {} - Missing `]` in indexing.", self.line, self.column, self.source))
                        }
                    }
                }
            },
            _ => {
                /* Must be `(´ */
                self.advance();
                match self.symbol {
                    Symbols::RightParen => {
                        self.advance();
                        Ok(Box::new(AST::Call(None)))
                    },
                    _ => {
                        let node = self.qualident()?;
                        match self.symbol {
                            Symbols::RightParen => {
                                self.advance();
                                Ok(Box::new(AST::Call(Some(node))))
                            },
                            _ => Err(format!("Syntax Error! At line: {}, column: {} in file: {} - Missing `]` in indexing.", self.line, self.column, self.source))
                        }
                    }
                }
            }
        }
    }

    fn expr_list(&mut self) -> Result<Box<AST>, String> {
        let left = self.expression()?;
        match self.symbol {
            Symbols::Comma => {
                let mut elements = Vec::<Box<AST>>::new();
                elements.push(left);
                self.advance();
                loop {
                    elements.push(self.expression()?);
                    match self.symbol {
                        Symbols::Comma => self.advance(),
                        _ => { break; }
                    }
                }
                Ok(Box::new(AST::ExprList(elements)))
            },
            _ => Ok(left)
        }
    }

    fn actual_parameters(&mut self) -> Result<Box<AST>, String> {
        self.advance();
        match self.symbol {
            Symbols::RightParen => {
                self.advance();
                Ok(Box::new(AST::ActualParameters(None)))
            },
            _ => {
                let left = self.expr_list()?;
                match self.symbol {
                    Symbols::RightParen => {
                        self.advance();
                        Ok(Box::new(AST::ActualParameters(Some(left))))
                    },
                    _ => Err(format!("Syntax Error! At line: {}, column: {} in file: {} - Missing closing parenthesis in parameters.", self.line, self.column, self.source))
                }
            }
        }
    }

    fn qualident(&mut self) -> Result<Box<AST>, String> {
        let first_line = self.line; let first_col = self.column; let first_name = self.buffer.clone();
        self.advance();
        match self.symbol {
            Symbols::Period => {
                self.advance();
                match self.symbol {
                    Symbols::Ident => {
                        let second_line = self.line; let second_col = self.column; let second_name = self.buffer.clone();
                        self.advance();
                        Ok(Box::new(AST::Qualident(first_line, first_col, first_name, second_line, second_col, second_name)))
                    },
                     _ => Err(format!("Syntax Error! At line: {}, column: {} in file: {} - Missing Name after `.`in qualident.", self.line, self.column, self.source))   
                }
            },
            _ => Ok(Box::new(AST::Name(first_line, first_col, first_name)))
        }
    }

    /* Statement rules */

    fn statement(&mut self) -> Result<Box<AST>, String> {
        match self.symbol {
            Symbols::Procedure => self.procedure_call(),
            Symbols::If => self.if_statement(),
            Symbols::Case => self.case_tatement(),
            Symbols::With => self.with_statement(),
            Symbols::Loop => self.loop_statement(),
            Symbols::Exit => self.exit_statement(),
            Symbols::Return => self.return_statement(),
            Symbols::While => self.while_statement(),
            Symbols::Repeat => self.repeat_statement(),
            Symbols::For => self.for_statement(),
            _ => self.assignment()
        }
    }

    fn if_statement(&mut self) -> Result<Box<AST>, String> {
        todo!()
    }

    fn case_tatement(&mut self) -> Result<Box<AST>, String> {
        todo!()
    }

    fn with_statement(&mut self) -> Result<Box<AST>, String> {
        todo!()
    }

    fn loop_statement(&mut self) -> Result<Box<AST>, String> {
        todo!()
    }

    fn exit_statement(&mut self) -> Result<Box<AST>, String> {
        todo!()
    }

    fn return_statement(&mut self) -> Result<Box<AST>, String> {
        todo!()
    }

    fn while_statement(&mut self) -> Result<Box<AST>, String> {
        todo!()
    }

    fn repeat_statement(&mut self) -> Result<Box<AST>, String> {
        todo!()
    }

    fn for_statement(&mut self) -> Result<Box<AST>, String> {
        todo!()
    }

    fn procedure_call(&mut self) -> Result<Box<AST>, String> {
        todo!()
    }

    fn assignment(&mut self) -> Result<Box<AST>, String> {
        todo!()
    }

    
}